config/routes.rb
Rails.application.routes.draw do
  
  post 'payments/create'


  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }
  
  resources :users
  
  resources :products do
    resources :comments
  end

  resources :payments
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/featured'

  post 'static_pages/thank_you'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 	root 'static_pages#featured'


	resources :orders, only: [:index, :show, :create, :destroy]

  mount ActionCable.server => '/cable'

end

app/models/product.rb
class Product < ApplicationRecord
	has_many :orders
	has_many :comments

	def highest_rating_comment
		self.comments.rating_desc.first
	end

	def lowest_rating_comment
		self.comments.rating_asc.first
	end

	def average_rating
		comments.average(:rating).to_f
	end

	def number_rating_comment
		self.comments.rating_desc.count
	end

	def self.search(search_term)
      if Rails.env.production?     	
        where("description ilike ? OR color ilike ? OR name ilike ?", "%#{search_term}%", "%#{search_term}%", "%#{search_term}%")
      else
        where("description LIKE ? OR color LIKE ? OR name LIKE ?", "%#{search_term}%", "%#{search_term}%", "%#{search_term}%")
      end  
	end

	validates :name, presence: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      @products = Product.search(params[:q]).paginate(:page => params[:page], :per_page => 12)
    else
      @products = Product.all.paginate(:page => params[:page], :per_page => 12)
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :description, :color, :image_url, :price)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end	
end

app/views/products/_comments.html.erb
<% @comments.each do |comment| %>

  <%= render 'comments/comment', comment: comment %>

<% end %>
<dd><%= will_paginate @comments %></dd>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal center product" } do |f| %>

  <% if @product.errors.any? %>
  <div class="col-sm-2">
  </div>
  <div class="col-sm-10" style="padding: 0;"> 
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
</div>
  <% end %>


  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => 'form-control' %>
      <%=f.error_span(:name) %>      
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :description, :class => 'form-control' %>
      <%=f.error_span(:description) %>      
    </div>
  </div>

  <div class="form-group">
    <%= f.label :color, :class => 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :color, :class => 'form-control' %>
      <%=f.error_span(:color) %>      
    </div>
  </div>

  <div class="form-group">
    <%= f.label :image_url, :class => 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :image_url, :class => 'form-control' %>
      <%=f.error_span(:image_url) %>      
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :price, :class => 'form-control' %>
      <%=f.error_span(:price) %>      
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>

  <dt><strong>Add a review</strong></dt><br/>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <dt><strong>
      <%= f.label :body, "Comment:" %></strong></dt>
      <dd>
      <%= f.text_area :body, class: "form-control new_comment_text" %>
    </dd>
    <dt><strong>
      <%= f.label :rating, "Rating:" %></strong></dt>
      <dd>
      <div class="rating"></div>
    </dd>
    <dd>
      <%= f.submit "Submit", class: "btn btn-default" %>
    </dd><br/>

    <dd><div class="notice" style="display:none" role="alert">A new comment was posted!</div></dd>

  <% end %>

<% end %>

app/views/products/_product.html.erb
<%- model_class = Product -%>
<div class="col-sm-4 col-md-3">
  <div class="product_box">
    <% cache ["v1", product] do %>
      <img class="img-responsive" src="<%=asset_path product.image_url %>" alt="<%=asset_path product.image_url %>">
      <h2><%= link_to product.name, product %></h2>
      <p style="min-height: 80px;"><%= product.description %></p>
      <div style="border-bottom: 1px solid black;">
        <p>Average rating:</p>
        <div style="min-height: 50px;">
        <div class="rated" data-score="<%= product.average_rating %>"></div> 
      </div>
      </div>
      <strong><%= number_to_currency(product.price, :unit => "€") %></strong>
    <% end %><!--end cache product -->
  </div>
</div><!-- /col -->

app/views/products/_stars.html.erb
<%if stars.blank? %>
 	<p style="min-height: 0; margin: 0;">This product has not been rated.</p>
 	<%else%>
  <%((stars*2).round(0)/2).floor.to_i.times do%>
    <i class="glyphicon glyphicon-star"></i>
  <%end%> 
  <%((((stars*2).round(0)/2)%1)*2).to_i.times do%>
    <i class="glyphicon glyphicon-star half"></i>
  <%end%>
  <%(5-(stars*2).round/2.floor-((((stars*2).round(0))/2)%1)*2).to_i.times do%>
      <i class="glyphicon glyphicon-star empty"></i>
  <%end%>
<%end%>          

app/views/products/edit.html.erb
<div class="container products">
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/products/index.html.erb
<div class="container products">
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>


  <div class="row">
  	<% cache ["v1-#{params[:page]}-#{params[:q]}", cache_key_for_products] do %>
    	<%= render @products %>
    <% end %><!-- end cache @products -->
  </div>

<%= will_paginate @products %>

</div><!--end container products-->

app/views/products/new.html.erb
<div class="container products">
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="container products">

  <dl class="dl-horizontal" style="max-width: 1000px;">

    <div class="page-header">
      <% cache @product do %>
      <h1><%=t '.title', :default => @product.name %></h1>
    </div>

    <div class="row" data-product-id="<%= @product.id %>">
      <div class = "col-sm-6 col-sm-push-6">
        <div style="max-width: 500px; margin: 0 auto">
          <img class="img-responsive img-zoom" src="<%=asset_path @product.image_url %>">
        </div>
      </div><!--end col-sm-6-->

      <div class="col-sm-6 col-sm-pull-6">
        <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
        <dd><%= @product.description %></dd>
        <dt><strong><%= model_class.human_attribute_name(:color) %>:</strong></dt>
        <dd><%= @product.color %></dd> 
        <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
        <dd><%= number_to_currency(@product.price, :unit => "€") %></dd> 
        <br>
        <% end %><!-- end cache product -->
        <% if user_signed_in? %>
          <dd><%= form_tag "/payments/create" do %>
              <%= render partial: "shared/stripe_checkout_button" %>
          <% end %></dd>
        <% else %>
          <dd><%= link_to('Login to buy', new_user_session_path, :class => 'stripe-button') %></dd>
        <% end %>
        <br>
        <dt><strong>Average rating:</strong></dt>
        <dd>
          <div id="average-rating" class="rated" data-score="<%= @product.average_rating %>"></div>  
        </dd>
      </div><!--end col-sm-6-->
    </div><!--end row-->

    <%= render :partial => 'new_comment' %>
    <dt><strong>Comments:</strong></dt>
    <div class="product-reviews">
           <%= render :partial => 'comments' %>
    </div>    
  </dl>



  <%= link_to t('.back', :default => t("helpers.links.back")), products_path, :class => 'btn btn-default'  %>
  <% if signed_in? && current_user.admin? %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(@product), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(@product), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger' %>
  <% end %>
</div>