config/routes.rb
Rails.application.routes.draw do
  
  post 'payments/create'


  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }
  
  resources :users
  
  resources :products do
    resources :comments
  end

  resources :payments
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/featured'

  post 'static_pages/thank_you'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 	root 'static_pages#featured'


	resources :orders, only: [:index, :show, :create, :destroy]

  mount ActionCable.server => '/cable'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CfTest</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <!-- <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
	  <header class="container" style="background-image: url(<%= asset_path 'wall.jpg' %>)">

	  		<div class="row">
					<div class="col-xs-4" style="padding: 0;">
		  		<a href="#" title="Back to top" id="logo">
		  			<%= image_tag("logo_s.png", class: "img-responsive") %>
		  		</a>
		  	</div>
		  	<div class="col-xs-8" style="text-align: right; padding-bottom: 10px; max-width: 400px; float: right;">

		  		<h2>Your source for used bikes in Berlin</h2>

				  <%= form_tag "/products", :method => 'get', class: 'input-group'  do %>
				    <%= text_field_tag :q, params[:q], class: 'form-control', placeholder: 'Search for...' %>
				    <span class="input-group-btn">
				      <%= submit_tag "search", class: "btn btn-default" %>
				    </span>
				  <% end %>

					<% if user_signed_in? %>
					 <div style="margin-top: 10px;">
					 <p style="display: inline-block;">You are logged in as:<br/><%= link_to(current_user.email, edit_user_registration_path, :style => 'color: white;') %></p> 
					 <%= link_to('Logout',  destroy_user_session_path, :method => :delete, :class => 'btn btn-default', :style => 'vertical-align: top;') %>
					</div>
					<% else %>
					  <%= link_to('Login', new_user_session_path, :class => 'btn btn-default', :style => 'margin-top: 10px;') %>
					<% end %>
					<% if notice %>
						<p class="notice" role="alert"><%= notice %></p>
					<% end %>
					<% if alert %>
						<p class="alert alert-info" role="alert" style="margin-bottom: 5px; margin-top: 5px; padding: 5px;"><%= alert %></p>
					<% end %>

				</div>
			</div>

			<nav>
				<a class="default <%= 'active' if (current_page?(root_path) or current_page?(static_pages_index_path)) %>" href="<%= static_pages_index_path %>">Home</a>
				<a class="default <%= 'active' if request.fullpath.start_with?('/products') %>" href="<%= products_path %>">Shop</a>
				<a class="default <%= 'active' if current_page?(static_pages_about_path) %>" href="<%= static_pages_about_path %>">About</a>
				<a class="default <%= 'active' if current_page?(static_pages_contact_path) %>" href="<%= static_pages_contact_path %>">Contact</a>
			</nav> 

		</header> 
			
    <%= yield %>

		<footer class="container" style="background-image: url(<%= asset_path 'wall.jpg' %>)">
			<div class="row">
				<div class="col-xs-6">
					<a href="#" title="Back to top">
		  			Back to top
		  		</a>
			  	<p style="margin-top: 70px;">&copy; 2015 Bike Berlin</p>
				</div><!--end col-sm-4-->
				<div class="col-xs-6" style="text-align: right;">
					<p>Bike Shop Berlin GmbH<br>
					Main Street 1</p>
					<p>12345 Berlin</p>
					<a href="mailto:shop@bikeberlin.de" class="link">shop@bikeberlin.de</a>
        	<p>030 - 2125 3201</p>
				</div><!--end col-sm-8-->
		  <div><!--end row-->
		</footer>

  </body>
</html>